/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.applet.*;
import java.awt.*;
import java.awt.event.*;

import database.CurrentProperty;
import database.CurrentUser;
import database.UserDatabase;
import functionality.ContactLoader;
import functionality.UserAuthenticator;

/**
 *
 * @author Hang Xu
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form LoginGUI2
     */
    public LoginGUI() {
        initComponents();
        System.out.println("Current user is "+CurrentUser.getID());
        System.out.println("Current property is "+CurrentProperty.getID());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameText = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        passWordText = new javax.swing.JPasswordField();
        inButton = new javax.swing.JButton();
        outButton = new javax.swing.JButton();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        userNameText.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        userNameText.setForeground(new java.awt.Color(204, 204, 255));
        userNameText.setText("Username");
        userNameText.setAutoscrolls(false);
        userNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameTextFocusLost(evt);
            }
        });

        logoLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("Roomies");

        passWordText.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        passWordText.setForeground(new java.awt.Color(204, 204, 255));
        passWordText.setEchoChar((char) 0); 
        passWordText.setText("Password");
        passWordText.setAutoscrolls(false);
        passWordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passWordTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passWordTextFocusLost(evt);
            }
        });
        passWordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passWordTextKeyPressed(evt);
            }
        });

        inButton.setText("IN");
        inButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inButtonActionPerformed(evt);
            }
        });

        outButton.setText("OUT");
        outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outButtonActionPerformed(evt);
            }
        });

        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inButton, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(outButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passWordText, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(passWordText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(outButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inButtonActionPerformed
        // TODO add your handling code here:
    	String inputusn = userNameText.getText().toLowerCase();
    	String inputpwd = String.valueOf(passWordText.getPassword());
    	UserAuthenticator uA = new UserAuthenticator(inputusn, inputpwd);
        if(uA.authenticate()) // if successfully log in, remove the login GUI, show the main GUI.
        {
        	CurrentUser.setID(uA.getUserID());
        	CurrentProperty.setID(uA.getPropertyID());
            MainGUI mainGUI = new MainGUI();      
            mainGUI.setVisible(true);
            this.dispose();
        }
        else { // if fail to login, pop up the warning. 
            WrongPopup wrongLoginInfo = new WrongPopup("You may wanna check what you typed");
            wrongLoginInfo.setVisible(true);
        }
    }//GEN-LAST:event_inButtonActionPerformed

    private void outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButtonActionPerformed
         System.exit(0);
    }//GEN-LAST:event_outButtonActionPerformed

    private void userNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFocusGained
          if (userNameText.getForeground()!=Color.black)
        {
            userNameText.setText(null);
            userNameText.setForeground(Color.black);
        }
    }//GEN-LAST:event_userNameTextFocusGained

    private void passWordTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passWordTextFocusGained
        // TODO add your handling code here:
    	passWordText.setEchoChar('*');
        passWordText.setText(null);
         passWordText.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_passWordTextFocusGained
// dealing with shortcut: press enter instead of clicking "in" button.
    private void passWordTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordTextKeyPressed
        int key = evt.getKeyCode(); 
        if(Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK))
    	logoLabel.setForeground(Color.red);
    else logoLabel.setForeground(Color.black);
        if (key == KeyEvent.VK_ENTER)
        {
        	String inputusn = userNameText.getText().toLowerCase();
        	String inputpwd = passWordText.getPassword().toString(); 
        	
        	UserAuthenticator uA = new UserAuthenticator(inputusn, inputpwd);
            if(uA.authenticate()) // if successfully log in, remove the login GUI, show the main GUI.
            {
                MainGUI mainGUI = new MainGUI();     
                mainGUI.setVisible(true);
                this.dispose();
            }
            else { // if fail to login, pop up the warning. 
                WrongPopup wrongLoginInfo = new WrongPopup("You may wanna check what you typed");
                wrongLoginInfo.setVisible(true);
            }
        }
    }//GEN-LAST:event_passWordTextKeyPressed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        RegisterChoiceGUI registerChoiceGUI = new RegisterChoiceGUI();
        registerChoiceGUI.setVisible(true);
    }//GEN-LAST:event_registerActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerMouseClicked

    private void userNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFocusLost
    	  if(userNameText.getText().equals("")){
              userNameText.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); 
              userNameText.setForeground(new java.awt.Color(204, 204, 255));
              userNameText.setText("Username");
          }
    }//GEN-LAST:event_userNameTextFocusLost

    private void passWordTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passWordTextFocusLost
    	 if(String.valueOf(passWordText.getPassword()).equals("")){
             passWordText.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); 
             passWordText.setForeground(new java.awt.Color(204, 204, 255));
             passWordText.setEchoChar((char) 0);
             passWordText.setText("Password");
         }
    }//GEN-LAST:event_passWordTextFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton outButton;
    private javax.swing.JPasswordField passWordText;
    private javax.swing.JButton register;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
