/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

import database.Address;
import database.Property;
import functionality.PropertySearcher;

/**
 *
 * @author Hang Xu
 */
public class NewProperty extends javax.swing.JFrame {
	static int MODE = 0; // when mode is 0, it means the GUI is in searching mode, when 1, means adding mode.

    /**
     * Creates new form NewProperty
     */
    public NewProperty() {
        initComponents();
    }
    
    public NewProperty(Property p){
    	initComponents();
    	this.streetLine1.setText(p.propertyAddress.streetLine1);
    	this.streetLine2.setText(p.propertyAddress.streetLine2);
    	this.aptNumber.setText(p.propertyAddress.aptNumber);
    	this.city.setText(p.propertyAddress.city);
    	this.state.setText(p.propertyAddress.state);
    	this.country.setText(p.propertyAddress.country);
    	this.zipcode.setText(p.propertyAddress.zipcode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchAndAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        streetLine1 = new javax.swing.JTextField();
        streetLine2 = new javax.swing.JTextField();
        aptNumber = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        zipcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        searchAndAdd.setText("Search");
        searchAndAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchAndAddMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please type");

        back.setText("back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("property address");

        streetLine1.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        streetLine1.setForeground(new java.awt.Color(204, 204, 255));
        streetLine1.setText("Street Line 1");

        streetLine2.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        streetLine2.setForeground(new java.awt.Color(204, 204, 255));
        streetLine2.setText("Street Line 2");

        aptNumber.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        aptNumber.setForeground(new java.awt.Color(204, 204, 255));
        aptNumber.setText("Apt Number");

        city.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        city.setForeground(new java.awt.Color(204, 204, 255));
        city.setText("City");

        state.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        state.setForeground(new java.awt.Color(204, 204, 255));
        state.setText("State");

        country.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        country.setForeground(new java.awt.Color(204, 204, 255));
        country.setText("Country");

        zipcode.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        zipcode.setForeground(new java.awt.Color(204, 204, 255));
        zipcode.setText("Zipcode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchAndAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(streetLine1)
                        .addGap(0, 0, 0)
                        .addComponent(streetLine2)
                        .addGap(0, 0, 0)
                        .addComponent(aptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(searchAndAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean PropertySearching(Property a) {
		PropertySearcher p = new PropertySearcher(a);
		return p.PropertyExists();
	}

	private Property ProertyInformationCollector() {
		Property userInputTemp = new Property(this.streetLine1.getText(),this.streetLine2.getText(),this.aptNumber.getText(),this.city.getText(),this.state.getText(),this.country.getText(),this.zipcode.getText(), null, null);
		return userInputTemp;
	}

	private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
       this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void searchAndAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchAndAddMouseClicked
    	 if(MODE == 0){// in searching mode
       	  Property userInputAddress = ProertyInformationCollector(); 
       	  boolean propertyExists = PropertySearching(userInputAddress);
       	  if(propertyExists){       
       		  MODE = 1;
       		  PropertyComfirmPopUp PropertyFound = new PropertyComfirmPopUp(MODE, userInputAddress);
       		  PropertyFound.setVisible(true);
       	  }
       	  else{
       		  PropertyComfirmPopUp PropertyNotFound = new PropertyComfirmPopUp(MODE,userInputAddress);
       		  PropertyNotFound.setVisible(true);   
       	  }
   		  this.dispose();
          }
    }//GEN-LAST:event_searchAndAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProperty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aptNumber;
    private javax.swing.JButton back;
    private javax.swing.JTextField city;
    private javax.swing.JTextField country;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton searchAndAdd;
    private javax.swing.JTextField state;
    private javax.swing.JTextField streetLine1;
    private javax.swing.JTextField streetLine2;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables
}
