/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;

/**
 *
 * @author Hang Xu
 */
public class NewProperty extends javax.swing.JFrame {

    /**
     * Creates new form NewProperty
     */
    public NewProperty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        streetLine1 = new javax.swing.JTextField();
        streetLine2 = new javax.swing.JTextField();
        aptNumber = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        state = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        zipcode = new javax.swing.JTextField();
        searchAndAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        streetLine1.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        streetLine1.setForeground(new java.awt.Color(204, 204, 255));
        streetLine1.setText("Street Line 1");
        streetLine1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetLine1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetLine1FocusLost(evt);
            }
        });
        streetLine1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                streetLine1MouseClicked(evt);
            }
        });
        streetLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetLine1ActionPerformed(evt);
            }
        });
        streetLine1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                streetLine1KeyPressed(evt);
            }
        });

        streetLine2.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        streetLine2.setForeground(new java.awt.Color(204, 204, 255));
        streetLine2.setText("Street Line 2");
        streetLine2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                streetLine2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                streetLine2FocusLost(evt);
            }
        });
        streetLine2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                streetLine2MouseClicked(evt);
            }
        });
        streetLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetLine2ActionPerformed(evt);
            }
        });
        streetLine2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                streetLine2KeyPressed(evt);
            }
        });

        aptNumber.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        aptNumber.setForeground(new java.awt.Color(204, 204, 255));
        aptNumber.setText("Apt Number");
        aptNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aptNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aptNumberFocusLost(evt);
            }
        });
        aptNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aptNumberMouseClicked(evt);
            }
        });
        aptNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptNumberActionPerformed(evt);
            }
        });
        aptNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aptNumberKeyPressed(evt);
            }
        });

        city.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        city.setForeground(new java.awt.Color(204, 204, 255));
        city.setText("City");
        city.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFocusLost(evt);
            }
        });
        city.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cityMouseClicked(evt);
            }
        });
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cityKeyPressed(evt);
            }
        });

        state.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        state.setForeground(new java.awt.Color(204, 204, 255));
        state.setText("State");
        state.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stateFocusLost(evt);
            }
        });
        state.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stateMouseClicked(evt);
            }
        });
        state.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateActionPerformed(evt);
            }
        });
        state.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stateKeyPressed(evt);
            }
        });

        country.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        country.setForeground(new java.awt.Color(204, 204, 255));
        country.setText("Country");
        country.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                countryFocusLost(evt);
            }
        });
        country.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryMouseClicked(evt);
            }
        });
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        country.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                countryKeyPressed(evt);
            }
        });

        zipcode.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        zipcode.setForeground(new java.awt.Color(204, 204, 255));
        zipcode.setText("Zipcode");
        zipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                zipcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                zipcodeFocusLost(evt);
            }
        });
        zipcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zipcodeMouseClicked(evt);
            }
        });
        zipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipcodeActionPerformed(evt);
            }
        });
        zipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                zipcodeKeyPressed(evt);
            }
        });

        searchAndAdd.setText("Search");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please type");

        back.setText("back");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("property address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(streetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchAndAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetLine1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetLine2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchAndAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(zipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void streetLine1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetLine1FocusGained
        // TODO add your handling code here:
        if(!streetLine1.getForeground().equals(Color.black)){
            streetLine1.setText(null);
            streetLine1.setForeground(Color.black);
        }
    }//GEN-LAST:event_streetLine1FocusGained

    private void streetLine1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetLine1FocusLost
        // TODO add your handling code here:
        if(streetLine1.getText().equals("")){
            streetLine1.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36));
            streetLine1.setForeground(new java.awt.Color(204, 204, 255));
            streetLine1.setText("Username");
        }
    }//GEN-LAST:event_streetLine1FocusLost

    private void streetLine1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_streetLine1MouseClicked
        // TODO add your handling code here:
        if(!streetLine1.getForeground().equals(Color.black)){
            streetLine1.setText(null);
            streetLine1.setForeground(Color.black);
        }
    }//GEN-LAST:event_streetLine1MouseClicked

    private void streetLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine1ActionPerformed

    private void streetLine1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetLine1KeyPressed
        // TODO add your handling code here:
        if (!streetLine1.getForeground().equals(Color.black))
        {
            streetLine1.setText(null);
            streetLine1.setForeground(Color.black);
        }
    }//GEN-LAST:event_streetLine1KeyPressed

    private void streetLine2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetLine2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine2FocusGained

    private void streetLine2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_streetLine2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine2FocusLost

    private void streetLine2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_streetLine2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine2MouseClicked

    private void streetLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine2ActionPerformed

    private void streetLine2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetLine2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetLine2KeyPressed

    private void aptNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aptNumberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_aptNumberFocusGained

    private void aptNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aptNumberFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_aptNumberFocusLost

    private void aptNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aptNumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aptNumberMouseClicked

    private void aptNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptNumberActionPerformed

    private void aptNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aptNumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptNumberKeyPressed

    private void cityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFocusGained

    private void cityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cityFocusLost

    private void cityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cityMouseClicked

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void cityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityKeyPressed

    private void stateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_stateFocusGained

    private void stateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_stateFocusLost

    private void stateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stateMouseClicked

    private void stateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateActionPerformed

    private void stateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateKeyPressed

    private void countryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFocusGained

    private void countryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFocusLost

    private void countryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_countryMouseClicked

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void countryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryKeyPressed

    private void zipcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipcodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeFocusGained

    private void zipcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_zipcodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeFocusLost

    private void zipcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zipcodeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeMouseClicked

    private void zipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeActionPerformed

    private void zipcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipcodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipcodeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProperty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProperty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aptNumber;
    private javax.swing.JButton back;
    private javax.swing.JTextField city;
    private javax.swing.JTextField country;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton searchAndAdd;
    private javax.swing.JTextField state;
    private javax.swing.JTextField streetLine1;
    private javax.swing.JTextField streetLine2;
    private javax.swing.JTextField zipcode;
    // End of variables declaration//GEN-END:variables
}
