/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;

/**
 *
 * @author Hang Xu
 */
public class WrongPopup extends javax.swing.JFrame {

    /**
     * Creates new form Wrong
     */
    public WrongPopup(String message ) {
        initComponents();
        this.wrongMessageLabel.setText(message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wrongMessageLabel = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wrongMessageLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        wrongMessageLabel.setForeground(new java.awt.Color(51, 204, 255));
        wrongMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrongMessageLabel.setText("jLabel1");
        wrongMessageLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wrongMessageLabelKeyPressed(evt);
            }
        });

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        OKButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OKButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OKButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(wrongMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(wrongMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void setText(String message)
    {
        wrongMessageLabel.setText(message);
    }
    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_OKButtonActionPerformed

    private void wrongMessageLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wrongMessageLabelKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_wrongMessageLabelKeyPressed

    private void OKButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OKButtonKeyPressed
        // TODO add your handling code here:
           int key = evt.getKeyCode(); 
        if (key == KeyEvent.VK_ENTER)
        {
            this.dispose();
        }
    }//GEN-LAST:event_OKButtonKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel wrongMessageLabel;
    // End of variables declaration//GEN-END:variables
}
