/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roomies.GUI;
import roomies.data.ID;
import roomies.Simulation.*;
import java.applet.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author Hang Xu
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI2
     */
    public LoginGUI() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameText = new javax.swing.JTextField();
        logoLabel = new javax.swing.JLabel();
        passWordText = new javax.swing.JPasswordField();
        inButton = new javax.swing.JButton();
        outButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        userNameText.setFont(new java.awt.Font("Franklin Gothic Book", 2, 36)); // NOI18N
        userNameText.setForeground(new java.awt.Color(204, 204, 255));
        userNameText.setText("Username");
        userNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameTextFocusGained(evt);
            }
        });
        userNameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameTextMouseClicked(evt);
            }
        });
        userNameText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                userNameTextInputMethodTextChanged(evt);
            }
        });
        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });
        userNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameTextKeyPressed(evt);
            }
        });

        logoLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("Roomies");

        passWordText.setFont(new java.awt.Font("Franklin Gothic Book", 2, 24)); // NOI18N
        passWordText.setForeground(new java.awt.Color(204, 204, 255));
        passWordText.setText("Password");
        passWordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passWordTextFocusGained(evt);
            }
        });
        passWordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordTextActionPerformed(evt);
            }
        });
        passWordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passWordTextKeyPressed(evt);
            }
        });

        inButton.setText("IN");
        inButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inButtonActionPerformed(evt);
            }
        });

        outButton.setText("OUT");
        outButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passWordText)
            .addGroup(layout.createSequentialGroup()
                .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(inButton, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(outButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(userNameText))
                .addGap(0, 0, 0)
                .addComponent(passWordText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inButton, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(outButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inButtonActionPerformed
        // TODO add your handling code here:
        LoginCheck loginCheck = new LoginCheck(userNameText.getText(),passWordText.getText());
        if(loginCheck.Check())
        {
            MainGUI mainGUI = new MainGUI();     
            mainGUI.setVisible(true);
            this.dispose();
            ID.setID(loginCheck.getNumber());
        }
        else { 
            Wrong wrongLoginInfo = new Wrong();
            wrongLoginInfo.setText("You may wanna check what you typed");
            wrongLoginInfo.setVisible(true);
        }
    }//GEN-LAST:event_inButtonActionPerformed

    private void outButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButtonActionPerformed
         System.exit(0);
    }//GEN-LAST:event_outButtonActionPerformed

    private void userNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameTextFocusGained
        // TODO add your handling code here:
       // userNameText.setText(null);
    }//GEN-LAST:event_userNameTextFocusGained

    private void passWordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passWordTextActionPerformed

    private void passWordTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passWordTextFocusGained
        // TODO add your handling code here:
        passWordText.setText(null);
         passWordText.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_passWordTextFocusGained

    private void userNameTextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_userNameTextInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_userNameTextInputMethodTextChanged

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_userNameTextActionPerformed

    private void userNameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTextMouseClicked
        // TODO add your handling code here:
             userNameText.setText(null);
             userNameText.setForeground(Color.black);
             
    }//GEN-LAST:event_userNameTextMouseClicked

    private void passWordTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordTextKeyPressed
        int key = evt.getKeyCode(); 
        if (key == KeyEvent.VK_ENTER)
        {
             LoginCheck loginCheck = new LoginCheck(userNameText.getText(),passWordText.getText());
        if(loginCheck.Check())
        {
            MainGUI mainGUI = new MainGUI();     
            mainGUI.setVisible(true);
            this.dispose();
            ID.setID(loginCheck.getNumber());
        }
        else { 
            Wrong wrongLoginInfo = new Wrong();
            wrongLoginInfo.setText("You may wanna check what you typed");
            wrongLoginInfo.setVisible(true);
        }
        }
    }//GEN-LAST:event_passWordTextKeyPressed

    private void userNameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTextKeyPressed
        // TODO add your handling code here:
        if (userNameText.getForeground()!=Color.black)
        {
            userNameText.setText(null);
            userNameText.setForeground(Color.black);
        }
    }//GEN-LAST:event_userNameTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton outButton;
    private javax.swing.JPasswordField passWordText;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
